# Generated by Django 3.0.3 on 2020-02-10 13:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Контент'),
        ),
    ]
